"""
Kaggriculture submission - single-file bundle, auto-generated by
tools/bundle.py from agent/constants.py + agent/market.py + agent/policy.py.
Edit those files and re-run the bundler, not this file directly.
"""
import math as _math

# ---------------- constants ----------------
CROPS = {
    "WHEAT":      {"seed": 10, "first_yield_day": 2, "max_yield_day": 4, "interval": 0, "max_yield": 6, "ongoing": False},
    "CARROT":     {"seed": 20, "first_yield_day": 2, "max_yield_day": 3, "interval": 0, "max_yield": 4, "ongoing": False},
    "TOMATO":     {"seed": 50, "first_yield_day": 8, "max_yield_day": 8, "interval": 1, "max_yield": 4, "ongoing": True},
    "STRAWBERRY": {"seed": 100, "first_yield_day": 10, "max_yield_day": 10, "interval": 2, "max_yield": 4, "ongoing": True},
    "MELON":      {"seed": 80, "first_yield_day": 10, "max_yield_day": 12, "interval": 0, "max_yield": 6, "ongoing": False},
}

ANIMALS = {
    "GOOSE": {"cost": 300, "structure": "COOP",    "first_yield_day": 4, "interval": 1, "max_held": 4, "product": "EGG"},
    "COW":   {"cost": 400, "structure": "PASTURE", "first_yield_day": 8, "interval": 2, "max_held": 6, "product": "MILK"},
    "SHEEP": {"cost": 500, "structure": "PASTURE", "first_yield_day": 6, "interval": 3, "max_held": 6, "product": "WOOL"},
}

PRODUCTS = ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON", "EGG", "MILK", "WOOL", "FERTILIZER"]

MARKET_I0 = 10000
PRICE_FLOOR = 1

MARKET_PARAMS = {
    "WHEAT":      {"base":  25, "I0": MARKET_I0, "T": 400, "below_func": "sqrt",   "below_target": 0.80, "above_func": "log",    "above_target": 0.20},
    "CARROT":     {"base":  35, "I0": MARKET_I0, "T": 450, "below_func": "log",    "below_target": 0.20, "above_func": "sqrt",   "above_target": 0.70},
    "TOMATO":     {"base":  60, "I0": MARKET_I0, "T": 200, "below_func": "linear", "below_target": 0.40, "above_func": "sqrt",   "above_target": 0.60},
    "STRAWBERRY": {"base": 120, "I0": MARKET_I0, "T": 100, "below_func": "sqrt",   "below_target": 0.70, "above_func": "linear", "above_target": 1.60},
    "MELON":      {"base": 250, "I0": MARKET_I0, "T": 300, "below_func": "log",    "below_target": 0.20, "above_func": "sq",     "above_target": 3.60},
    "EGG":        {"base":  50, "I0": MARKET_I0, "T": 332, "below_func": "linear", "below_target": 0.40, "above_func": "log",    "above_target": 0.20},
    "MILK":       {"base": 160, "I0": MARKET_I0, "T": 122, "below_func": "sqrt",   "below_target": 0.60, "above_func": "linear", "above_target": 1.60},
    "WOOL":       {"base": 200, "I0": MARKET_I0, "T": 105, "below_func": "log",    "below_target": 0.20, "above_func": "sq",     "above_target": 3.20},
    "FERTILIZER": {"base": 100, "I0": MARKET_I0, "T": 200, "below_func": "linear", "below_target": 0.40, "above_func": "linear", "above_target": 0.40},
}

LAND_ORDER = ["NE", "SW", "SE"]
LAND_PRICES = [1000, 2000, 4000]
FARM_HAND_COST_MULT = 1

SHOPS = {
    "BAKERY":         ["EGG", "WHEAT"],
    "PIZZA_SHOP":     ["MILK", "TOMATO", "WHEAT"],
    "BRUNCH_SPOT":    ["EGG", "WHEAT", "STRAWBERRY"],
    "YARN_STORE":     ["WOOL"],
    "ICE_CREAM_SHOP": ["STRAWBERRY", "MILK", "WHEAT"],
    "PET_CAFE":       ["CARROT"],
    "SMOOTHIE_SHOP":  ["STRAWBERRY", "MILK"],
    "FARMERS_MARKET": ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY"],
}

TURNS_PER_DAY = 24
EPISODE_STEPS = 720
SEASON_DAYS = 30


def fib_cost(n, mult=FARM_HAND_COST_MULT):
    """Cost of the n-th hire today (1-indexed). fib(1)=1, fib(2)=1, fib(3)=2..."""
    a, b = 1, 1
    for _ in range(n - 1):
        a, b = b, a + b
    return mult * a


def market_price(item, inventory, params=None):
    """Exact replica of the engine's price curve so the agent can price-forecast."""
    import math
    p = (params or MARKET_PARAMS)[item]
    base, I0, T = p["base"], p["I0"], p["T"]

    def shape(func, x):
        x = max(0.0, x)
        if func == "linear": return x
        if func == "sq":     return x * x
        if func == "sqrt":   return math.sqrt(x)
        if func == "log":    return math.log(1.0 + x)
        if func == "log10":  return math.log10(1.0 + x)
        return x

    if inventory < I0:
        f = p["below_func"]
        amp = p["below_target"] * base / shape(f, T)
        price = base + amp * shape(f, I0 - inventory)
    else:
        f = p["above_func"]
        amp = p["above_target"] * base / shape(f, T)
        price = base - amp * shape(f, inventory - I0)
    return max(PRICE_FLOOR, int(round(price)))


# ---------------- market ----------------


def simulate_sell_revenue(item, quantity, market_inventory, params=None, max_qty=None):
    """Returns (total_revenue, revenue_per_unit_curve) for selling `quantity`
    units of `item`, walking the price down one unit at a time exactly like
    the real engine does. Cheap: O(quantity), fine for shed-sized batches.
    """
    if quantity <= 0:
        return 0, []
    inv = market_inventory
    total = 0
    curve = []
    n = quantity if max_qty is None else min(quantity, max_qty)
    for _ in range(n):
        price = market_price(item, inv, params)
        total += price
        curve.append(price)
        inv += 1  # selling adds to market inventory (moves toward glut)
    return total, curve


def best_sell_batch(item, shed_qty, market_inventory, params=None, min_marginal_price=1):
    """Find the largest quantity worth selling right now: keep adding units
    while the marginal (next-unit) price stays >= min_marginal_price.
    Returns (qty_to_sell, expected_revenue).
    Use min_marginal_price > floor to avoid dumping the whole shed into a
    single crashed order - e.g. pass current price * 0.5 as a floor to stop
    once you've pushed the price down by half.
    """
    if shed_qty <= 0:
        return 0, 0
    inv = market_inventory
    qty = 0
    revenue = 0
    for _ in range(shed_qty):
        price = market_price(item, inv, params)
        if price < min_marginal_price:
            break
        revenue += price
        inv += 1
        qty += 1
    return qty, revenue


def buy_cost(item, quantity, market_inventory, params=None):
    """Mirror of simulate_sell_revenue but for BUY_PRODUCT (wheat/fertilizer
    only). Buying drains inventory (moves toward scarcity), raising price.
    """
    if quantity <= 0:
        return 0
    inv = market_inventory
    total = 0
    for _ in range(quantity):
        price = market_price(item, inv, params)
        total += price
        inv = max(0, inv - 1)
    return total


# ---------------- policy ----------------

MOVES = {"NORTH": (0, -1), "SOUTH": (0, 1), "EAST": (1, 0), "WEST": (-1, 0)}

# Below this many remaining turns, stop starting anything that can't cash
# out in time. Computed per-candidate against days_left, not just a flat
# number, but this is the hard backstop.
SAFETY_MARGIN_TURNS = 6


def _dist(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def _step_toward(pos, target):
    dx = target[0] - pos[0]
    dy = target[1] - pos[1]
    if dx == 0 and dy == 0:
        return "PASS"
    # Move along the axis with the larger gap first (irrelevant for cost
    # since it's Manhattan distance either way, but keeps behavior stable).
    if abs(dx) >= abs(dy) and dx != 0:
        return "EAST" if dx > 0 else "WEST"
    return "SOUTH" if dy > 0 else "NORTH"


def _turns_left(day, hour):
    return EPISODE_STEPS - (day * TURNS_PER_DAY + hour)


def _days_left(day):
    return SEASON_DAYS - day


def _quadrant_of(x, y, board_size):
    half = board_size // 2
    if x < half and y < half: return "NW"
    if x >= half and y < half: return "NE"
    if x < half and y >= half: return "SW"
    return "SE"


def _worker_positions(farm):
    positions = [tuple(farm["farmer"])]
    positions += [tuple(h) for h in farm.get("hands", [])]
    return positions


def _find_survival_tasks(farm, board_size):
    """Anything that dies tonight if ignored. Highest priority, always."""
    tasks = []
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if not isinstance(tile, dict):
                continue
            if tile.get("kind") == "PLANT" and not tile.get("watered_today") \
               and tile.get("consecutive_unwatered", 0) >= 1:
                tasks.append({"pos": (x, y), "action": "WATER", "value": 5000, "kind": "survival"})
            elif tile.get("kind") in ("COOP", "PASTURE") and tile.get("animal") \
                 and not tile.get("fed_today") and tile.get("consecutive_unfed", 0) >= 1:
                tasks.append({"pos": (x, y), "action": "FEED", "value": 5000, "kind": "survival"})
    return tasks


def _find_harvest_tasks(farm):
    tasks = []
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if not isinstance(tile, dict):
                continue
            if tile.get("yield_units", 0) > 0:
                # Rough value: units * a conservative product base price.
                # (Real revenue is computed properly at sell time via market.py;
                # this is only used to rank harvest vs other tasks.)
                if tile["kind"] == "PLANT":
                    item = tile["crop"]
                else:
                    item = ANIMALS[tile["animal"]]["product"]
                est_price = MARKET_PARAMS[item]["base"]
                tasks.append({
                    "pos": (x, y), "action": "HARVEST",
                    "value": tile["yield_units"] * est_price * 0.9,
                    "kind": "harvest",
                })
    return tasks


def _find_water_tasks(farm):
    """Plants not yet dying but unwatered today - worth doing if nothing
    more urgent, since watering during the bonus window adds yield."""
    tasks = []
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if isinstance(tile, dict) and tile.get("kind") == "PLANT" and not tile.get("watered_today"):
                tasks.append({"pos": (x, y), "action": "WATER", "value": 15, "kind": "water"})
    return tasks


def _find_care_tasks(farm):
    tasks = []
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if isinstance(tile, dict) and tile.get("kind") in ("COOP", "PASTURE") \
               and tile.get("animal") and tile.get("fed_today") and not tile.get("cared_today"):
                tasks.append({"pos": (x, y), "action": "CARE", "value": 10, "kind": "care"})
    return tasks


def _best_crop_to_plant(money, days_left, turns_left):
    """ROI-ranked crop choice, filtered by whether it can pay off before
    season end (terminal liquidation awareness)."""
    candidates = []
    for crop, cd in CROPS.items():
        if cd["seed"] > money:
            continue
        # A crop needs first_yield_day days to pay anything, plus ~1 day
        # margin to travel+harvest+sell. If that doesn't fit, skip it.
        if days_left < cd["first_yield_day"] + 1:
            continue
        est_price = MARKET_PARAMS[crop]["base"]
        # crude total value estimate: max_yield * price, discounted if it's
        # an ongoing crop that likely won't reach full scheduled yields
        # given remaining days.
        value = cd["max_yield"] * est_price
        payoff_days = max(cd["max_yield_day"], cd["first_yield_day"])
        roi_per_day = (value - cd["seed"]) / max(1, payoff_days)
        candidates.append((roi_per_day, crop))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]


def _find_empty_tiles(farm, board_size):
    empties = []
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if tile is None:
                empties.append((x, y))
    return empties


def agent(obs):
    farms = obs.get("farms", [])
    player = obs.get("player", 0)
    private = obs.get("private", {}) or {}
    market = obs.get("market", {}) or {}
    day = obs.get("day", 0)
    hour = obs.get("hour", 0)

    if not farms or player >= len(farms):
        return {"farmer": ["PASS"], "hands": [], "market": []}

    farm = farms[player]
    board_size = len(farm["tiles"])
    money = farm["money"]
    shed = private.get("shed", {})
    seeds = private.get("seeds", {})
    m_inv = market.get("inventory", {})
    m_params = market.get("params")

    turns_left = _turns_left(day, hour)
    days_left = _days_left(day)
    in_liquidation = turns_left <= SAFETY_MARGIN_TURNS * 4  # last ~1 day: stop investing

    # ---------- MARKET ORDERS (sell shed inventory, price-aware) ----------
    market_orders = []
    orders_used = 0
    max_orders = 10
    for item, qty in shed.items():
        if qty <= 0 or orders_used >= max_orders:
            continue
        inv = m_inv.get(item, MARKET_I0)
        cur_price = market_price(item, inv, m_params)
        # Don't crash the price selling our own batch: stop once marginal
        # price drops below 60% of the pre-sale price (tunable), UNLESS
        # we're in end-game liquidation, where anything above the floor
        # is worth taking since unsold stock is worth exactly $0 at turn 720.
        floor = PRICE_FLOOR if in_liquidation else max(PRICE_FLOOR, int(cur_price * 0.6))
        sell_qty, _ = best_sell_batch(item, qty, inv, m_params, min_marginal_price=floor)
        if sell_qty > 0:
            market_orders.append(["SELL", item, sell_qty])
            orders_used += 1

    # Buy seed for next planting decision (decided below) happens after we
    # know what workers will need; kept simple here - see planting task.

    # ---------- BUILD TASK LIST ----------
    tasks = _find_survival_tasks(farm, board_size)
    tasks += _find_harvest_tasks(farm)
    tasks += _find_care_tasks(farm)
    if not in_liquidation:
        tasks += _find_water_tasks(farm)

    # Planting: only propose if not in liquidation and there's an empty tile
    # and we can afford + have runway to profit.
    if not in_liquidation:
        crop = _best_crop_to_plant(money, days_left, turns_left)
        empties = _find_empty_tiles(farm, board_size)
        if crop and empties:
            need_seed = seeds.get(crop, 0) <= 0
            if need_seed and money >= CROPS[crop]["seed"] and orders_used < max_orders:
                market_orders.append(["BUY_SEED", crop, 1])
                orders_used += 1
            if seeds.get(crop, 0) > 0 or need_seed:
                # Plant on the nearest empty tile (task list picks nearest worker anyway)
                tasks.append({"pos": empties[0], "action": "PLANT", "crop": crop,
                               "value": 40, "kind": "plant"})

    # ---------- ASSIGN WORKERS TO TASKS (greedy, nearest-highest-value) --
    workers = _worker_positions(farm)
    assigned = [None] * len(workers)
    used_tasks = set()

    # Sort tasks by value desc so high-value tasks get first pick of nearest worker
    tasks.sort(key=lambda t: -t["value"])
    for t in tasks:
        tkey = t["pos"]
        if tkey in used_tasks:
            continue
        # find nearest unassigned worker
        best_w, best_d = None, None
        for wi, wpos in enumerate(workers):
            if assigned[wi] is not None:
                continue
            d = _dist(wpos, t["pos"])
            if best_d is None or d < best_d:
                best_w, best_d = wi, d
        if best_w is None:
            break
        assigned[best_w] = t
        used_tasks.add(tkey)

    # ---------- CONVERT ASSIGNMENTS TO ACTIONS ----------
    def action_for(wi):
        t = assigned[wi]
        wpos = workers[wi]
        if t is None:
            return ["PASS"]
        if wpos != t["pos"]:
            return [_step_toward(wpos, t["pos"])]
        if t["action"] == "PLANT":
            return ["PLANT", t["crop"]]
        return [t["action"]]

    farmer_action = action_for(0)
    hands_actions = [action_for(i) for i in range(1, len(workers))]

    return {"farmer": farmer_action, "hands": hands_actions, "market": market_orders[:max_orders]}
