"""
Kaggriculture submission - single-file bundle, auto-generated by
tools/bundle.py from agent/constants.py + agent/market.py + agent/policy.py.
Edit those files and re-run the bundler, not this file directly.
"""
import math as _math

# ---------------- constants ----------------
CROPS = {
    "WHEAT":      {"seed": 10, "first_yield_day": 2, "max_yield_day": 4, "interval": 0, "max_yield": 6, "ongoing": False},
    "CARROT":     {"seed": 20, "first_yield_day": 2, "max_yield_day": 3, "interval": 0, "max_yield": 4, "ongoing": False},
    "TOMATO":     {"seed": 50, "first_yield_day": 8, "max_yield_day": 8, "interval": 1, "max_yield": 4, "ongoing": True},
    "STRAWBERRY": {"seed": 100, "first_yield_day": 10, "max_yield_day": 10, "interval": 2, "max_yield": 4, "ongoing": True},
    "MELON":      {"seed": 80, "first_yield_day": 10, "max_yield_day": 12, "interval": 0, "max_yield": 6, "ongoing": False},
}

ANIMALS = {
    "GOOSE": {"cost": 300, "structure": "COOP",    "first_yield_day": 4, "interval": 1, "max_held": 4, "product": "EGG"},
    "COW":   {"cost": 400, "structure": "PASTURE", "first_yield_day": 8, "interval": 2, "max_held": 6, "product": "MILK"},
    "SHEEP": {"cost": 500, "structure": "PASTURE", "first_yield_day": 6, "interval": 3, "max_held": 6, "product": "WOOL"},
}

PRODUCTS = ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON", "EGG", "MILK", "WOOL", "FERTILIZER"]

MARKET_I0 = 10000
PRICE_FLOOR = 1

MARKET_PARAMS = {
    "WHEAT":      {"base":  25, "I0": MARKET_I0, "T": 400, "below_func": "sqrt",   "below_target": 0.80, "above_func": "log",    "above_target": 0.20},
    "CARROT":     {"base":  35, "I0": MARKET_I0, "T": 450, "below_func": "log",    "below_target": 0.20, "above_func": "sqrt",   "above_target": 0.70},
    "TOMATO":     {"base":  60, "I0": MARKET_I0, "T": 200, "below_func": "linear", "below_target": 0.40, "above_func": "sqrt",   "above_target": 0.60},
    "STRAWBERRY": {"base": 120, "I0": MARKET_I0, "T": 100, "below_func": "sqrt",   "below_target": 0.70, "above_func": "linear", "above_target": 1.60},
    "MELON":      {"base": 250, "I0": MARKET_I0, "T": 300, "below_func": "log",    "below_target": 0.20, "above_func": "sq",     "above_target": 3.60},
    "EGG":        {"base":  50, "I0": MARKET_I0, "T": 332, "below_func": "linear", "below_target": 0.40, "above_func": "log",    "above_target": 0.20},
    "MILK":       {"base": 160, "I0": MARKET_I0, "T": 122, "below_func": "sqrt",   "below_target": 0.60, "above_func": "linear", "above_target": 1.60},
    "WOOL":       {"base": 200, "I0": MARKET_I0, "T": 105, "below_func": "log",    "below_target": 0.20, "above_func": "sq",     "above_target": 3.20},
    "FERTILIZER": {"base": 100, "I0": MARKET_I0, "T": 200, "below_func": "linear", "below_target": 0.40, "above_func": "linear", "above_target": 0.40},
}

LAND_ORDER = ["NE", "SW", "SE"]
LAND_PRICES = [1000, 2000, 4000]
FARM_HAND_COST_MULT = 1

SHOPS = {
    "BAKERY":         ["EGG", "WHEAT"],
    "PIZZA_SHOP":     ["MILK", "TOMATO", "WHEAT"],
    "BRUNCH_SPOT":    ["EGG", "WHEAT", "STRAWBERRY"],
    "YARN_STORE":     ["WOOL"],
    "ICE_CREAM_SHOP": ["STRAWBERRY", "MILK", "WHEAT"],
    "PET_CAFE":       ["CARROT"],
    "SMOOTHIE_SHOP":  ["STRAWBERRY", "MILK"],
    "FARMERS_MARKET": ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY"],
}

TURNS_PER_DAY = 24
EPISODE_STEPS = 720
SEASON_DAYS = 30


def fib_cost(n, mult=FARM_HAND_COST_MULT):
    """Cost of the n-th hire today (1-indexed). fib(1)=1, fib(2)=1, fib(3)=2..."""
    a, b = 1, 1
    for _ in range(n - 1):
        a, b = b, a + b
    return mult * a


def market_price(item, inventory, params=None):
    """Exact replica of the engine's price curve so the agent can price-forecast."""
    import math
    p = (params or MARKET_PARAMS)[item]
    base, I0, T = p["base"], p["I0"], p["T"]

    def shape(func, x):
        x = max(0.0, x)
        if func == "linear": return x
        if func == "sq":     return x * x
        if func == "sqrt":   return math.sqrt(x)
        if func == "log":    return math.log(1.0 + x)
        if func == "log10":  return math.log10(1.0 + x)
        return x

    if inventory < I0:
        f = p["below_func"]
        amp = p["below_target"] * base / shape(f, T)
        price = base + amp * shape(f, I0 - inventory)
    else:
        f = p["above_func"]
        amp = p["above_target"] * base / shape(f, T)
        price = base - amp * shape(f, inventory - I0)
    return max(PRICE_FLOOR, int(round(price)))


# ---------------- market ----------------


def simulate_sell_revenue(item, quantity, market_inventory, params=None, max_qty=None):
    """Returns (total_revenue, revenue_per_unit_curve) for selling `quantity`
    units of `item`, walking the price down one unit at a time exactly like
    the real engine does. Cheap: O(quantity), fine for shed-sized batches.
    """
    if quantity <= 0:
        return 0, []
    inv = market_inventory
    total = 0
    curve = []
    n = quantity if max_qty is None else min(quantity, max_qty)
    for _ in range(n):
        price = market_price(item, inv, params)
        total += price
        curve.append(price)
        inv += 1  # selling adds to market inventory (moves toward glut)
    return total, curve


def best_sell_batch(item, shed_qty, market_inventory, params=None, min_marginal_price=1):
    """Find the largest quantity worth selling right now: keep adding units
    while the marginal (next-unit) price stays >= min_marginal_price.
    Returns (qty_to_sell, expected_revenue).
    Use min_marginal_price > floor to avoid dumping the whole shed into a
    single crashed order - e.g. pass current price * 0.5 as a floor to stop
    once you've pushed the price down by half.
    """
    if shed_qty <= 0:
        return 0, 0
    inv = market_inventory
    qty = 0
    revenue = 0
    for _ in range(shed_qty):
        price = market_price(item, inv, params)
        if price < min_marginal_price:
            break
        revenue += price
        inv += 1
        qty += 1
    return qty, revenue


def buy_cost(item, quantity, market_inventory, params=None):
    """Mirror of simulate_sell_revenue but for BUY_PRODUCT (wheat/fertilizer
    only). Buying drains inventory (moves toward scarcity), raising price.
    """
    if quantity <= 0:
        return 0
    inv = market_inventory
    total = 0
    for _ in range(quantity):
        price = market_price(item, inv, params)
        total += price
        inv = max(0, inv - 1)
    return total


# ---------------- policy ----------------

MOVES = {"NORTH": (0, -1), "SOUTH": (0, 1), "EAST": (1, 0), "WEST": (-1, 0)}
SAFETY_MARGIN_TURNS = 6
MAX_ANIMALS_V1 = 4           # cap ambition for v1 - avoid overcommitting to a
                              # pipeline we haven't proven yet on a real ladder
ANIMAL_PRIORITY = ["GOOSE", "COW", "SHEEP"]  # cheap entry first, then better payback


def _dist(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def _step_toward(pos, target):
    dx, dy = target[0] - pos[0], target[1] - pos[1]
    if dx == 0 and dy == 0:
        return "PASS"
    if abs(dx) >= abs(dy) and dx != 0:
        return "EAST" if dx > 0 else "WEST"
    return "SOUTH" if dy > 0 else "NORTH"


def _turns_left(day, hour):
    return EPISODE_STEPS - (day * TURNS_PER_DAY + hour)


def _days_left(day):
    return SEASON_DAYS - day


def _worker_positions(farm):
    return [tuple(farm["farmer"])] + [tuple(h) for h in farm.get("hands", [])]


def _shed_adjacent_tile(board_size):
    half = board_size // 2
    return (half - 1, half - 1)  # always valid: NW quadrant is always unlocked


def _find_survival_tasks(farm):
    tasks = []
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if not isinstance(tile, dict):
                continue
            if tile.get("kind") == "PLANT" and not tile.get("watered_today") \
               and tile.get("consecutive_unwatered", 0) >= 1:
                tasks.append({"pos": (x, y), "action": "WATER", "value": 5000, "kind": "survival"})
            elif tile.get("kind") in ("COOP", "PASTURE") and tile.get("animal") \
                 and not tile.get("fed_today") and tile.get("consecutive_unfed", 0) >= 1:
                tasks.append({"pos": (x, y), "action": "FEED", "value": 5000, "kind": "survival"})
    return tasks


def _find_harvest_tasks(farm):
    tasks = []
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if not isinstance(tile, dict) or tile.get("yield_units", 0) <= 0:
                continue
            item = tile["crop"] if tile["kind"] == "PLANT" else ANIMALS[tile["animal"]]["product"]
            est_price = MARKET_PARAMS[item]["base"]
            tasks.append({"pos": (x, y), "action": "HARVEST",
                           "value": tile["yield_units"] * est_price * 0.9, "kind": "harvest"})
    return tasks


def _find_water_tasks(farm):
    tasks = []
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if isinstance(tile, dict) and tile.get("kind") == "PLANT" and not tile.get("watered_today"):
                tasks.append({"pos": (x, y), "action": "WATER", "value": 15, "kind": "water"})
    return tasks


def _find_care_tasks(farm):
    tasks = []
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if isinstance(tile, dict) and tile.get("kind") in ("COOP", "PASTURE") \
               and tile.get("animal") and tile.get("fed_today") and not tile.get("cared_today"):
                tasks.append({"pos": (x, y), "action": "CARE", "value": 10, "kind": "care"})
    return tasks


def _best_crop_to_plant(money, days_left):
    candidates = []
    for crop, cd in CROPS.items():
        if cd["seed"] > money or days_left < cd["first_yield_day"] + 1:
            continue
        est_price = MARKET_PARAMS[crop]["base"]
        value = cd["max_yield"] * est_price
        payoff_days = max(cd["max_yield_day"], cd["first_yield_day"])
        roi_per_day = (value - cd["seed"]) / max(1, payoff_days)
        candidates.append((roi_per_day, crop))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]


def _find_empty_tiles(farm):
    return [(x, y) for y, row in enumerate(farm["tiles"]) for x, t in enumerate(row) if t is None]


def _animal_structure_state(farm):
    """Returns (counts_by_animal, empty_coop_pos, empty_pasture_pos)."""
    counts = {"GOOSE": 0, "COW": 0, "SHEEP": 0}
    empty_coop, empty_pasture = None, None
    for y, row in enumerate(farm["tiles"]):
        for x, tile in enumerate(row):
            if not isinstance(tile, dict):
                continue
            if tile.get("kind") == "COOP":
                if tile.get("animal"):
                    counts["GOOSE"] += 1
                elif empty_coop is None:
                    empty_coop = (x, y)
            elif tile.get("kind") == "PASTURE":
                if tile.get("animal"):
                    counts[tile["animal"]] += 1
                elif empty_pasture is None:
                    empty_pasture = (x, y)
    return counts, empty_coop, empty_pasture


def _decide_animal_target(farm, money, days_left):
    counts, empty_coop, empty_pasture = _animal_structure_state(farm)
    total = sum(counts.values())
    if total >= MAX_ANIMALS_V1 or days_left < 6:
        return None, empty_coop, empty_pasture
    for animal in ANIMAL_PRIORITY:
        cd = ANIMALS[animal]
        if counts[animal] == 0 and money >= cd["cost"] + 100:
            return animal, empty_coop, empty_pasture
    if money >= ANIMALS["GOOSE"]["cost"] + 200:
        return "GOOSE", empty_coop, empty_pasture
    return None, empty_coop, empty_pasture


def _consider_buy_land(farm, money, days_left):
    unlocked = farm.get("unlocked_quadrants", ["NW"])
    n_extra = len(unlocked) - 1
    if n_extra >= len(LAND_ORDER) or days_left < 8:
        return False
    price = LAND_PRICES[n_extra]
    if money < price + 500:
        return False
    total_unlocked = occupied = 0
    for row in farm["tiles"]:
        for tile in row:
            if tile != "LOCKED":
                total_unlocked += 1
                if tile is not None:
                    occupied += 1
    return total_unlocked > 0 and (occupied / total_unlocked) > 0.75


def agent(obs):
    farms = obs.get("farms", [])
    player = obs.get("player", 0)
    private = obs.get("private", {}) or {}
    market = obs.get("market", {}) or {}
    day = obs.get("day", 0)
    hour = obs.get("hour", 0)

    if not farms or player >= len(farms):
        return {"farmer": ["PASS"], "hands": [], "market": []}

    farm = farms[player]
    board_size = len(farm["tiles"])
    money = farm["money"]
    shed = private.get("shed", {})
    seeds = private.get("seeds", {})
    inventories = private.get("inventories", [])
    m_inv = market.get("inventory", {})
    m_params = market.get("params")

    turns_left = _turns_left(day, hour)
    days_left = _days_left(day)
    in_liquidation = turns_left <= SAFETY_MARGIN_TURNS * 4

    market_orders = []
    orders_used = 0
    max_orders = 10

    # ---------- SELL shed inventory, price-aware ----------
    for item, qty in shed.items():
        if qty <= 0 or orders_used >= max_orders or item in ("GOOSE", "COW", "SHEEP"):
            continue  # animals waiting in shed to be placed are not for sale
        inv = m_inv.get(item, MARKET_I0)
        cur_price = market_price(item, inv, m_params)
        floor = PRICE_FLOOR if in_liquidation else max(PRICE_FLOOR, int(cur_price * 0.6))
        sell_qty, _ = best_sell_batch(item, qty, inv, m_params, min_marginal_price=floor)
        if sell_qty > 0:
            market_orders.append(["SELL", item, sell_qty])
            orders_used += 1

    # ---------- BUILD TASK LIST ----------
    tasks = _find_survival_tasks(farm)
    tasks += _find_harvest_tasks(farm)
    tasks += _find_care_tasks(farm)
    if not in_liquidation:
        tasks += _find_water_tasks(farm)

    # ---- Planting ----
    if not in_liquidation:
        crop = _best_crop_to_plant(money, days_left)
        empties = _find_empty_tiles(farm)
        if crop and empties:
            need_seed = seeds.get(crop, 0) <= 0
            if need_seed and money >= CROPS[crop]["seed"] and orders_used < max_orders:
                market_orders.append(["BUY_SEED", crop, 1])
                orders_used += 1
            if seeds.get(crop, 0) > 0 or need_seed:
                tasks.append({"pos": empties[0], "action": "PLANT", "crop": crop,
                               "value": 45, "kind": "plant"})

    # ---- Animal investment pipeline (v1 addition) ----
    if not in_liquidation:
        target_animal, empty_coop, empty_pasture = _decide_animal_target(farm, money, days_left)
        if target_animal:
            structure = ANIMALS[target_animal]["structure"]
            empty_structure = empty_coop if structure == "COOP" else empty_pasture
            if empty_structure is None:
                empties = _find_empty_tiles(farm)
                if empties:
                    op = "BUILD_COOP" if structure == "COOP" else "BUILD_PASTURE"
                    tasks.append({"pos": empties[0], "action": op, "value": 60, "kind": "build"})
            else:
                shed_qty = shed.get(target_animal, 0)
                carrying_worker = None
                for wi, winv in enumerate(inventories):
                    if isinstance(winv, dict) and winv.get(target_animal, 0) > 0:
                        carrying_worker = wi
                        break
                if carrying_worker is not None:
                    tasks.append({"pos": empty_structure, "action": "PLACE", "item": target_animal,
                                   "value": 80, "kind": "place", "restrict_worker": carrying_worker})
                elif shed_qty > 0:
                    tasks.append({"pos": _shed_adjacent_tile(board_size), "action": "PICKUP",
                                   "item": target_animal, "value": 70, "kind": "pickup"})
                elif money >= ANIMALS[target_animal]["cost"] and orders_used < max_orders:
                    market_orders.append(["BUY_ANIMAL", target_animal, 1])
                    orders_used += 1

    # ---- Land expansion (v1 addition) ----
    if not in_liquidation and orders_used < max_orders and _consider_buy_land(farm, money, days_left):
        market_orders.append(["BUY_LAND"])
        orders_used += 1

    # ---------- ASSIGN WORKERS TO TASKS ----------
    workers = _worker_positions(farm)
    assigned = [None] * len(workers)
    used_tasks = set()

    tasks.sort(key=lambda t: -t["value"])
    for t in tasks:
        tkey = (t["pos"], t.get("action"))
        if tkey in used_tasks:
            continue
        restrict = t.get("restrict_worker")
        candidate_indices = [restrict] if restrict is not None else range(len(workers))
        best_w, best_d = None, None
        for wi in candidate_indices:
            if wi >= len(workers) or assigned[wi] is not None:
                continue
            d = _dist(workers[wi], t["pos"])
            if best_d is None or d < best_d:
                best_w, best_d = wi, d
        if best_w is None:
            continue
        assigned[best_w] = t
        used_tasks.add(tkey)

    # ---- HIRE decision (v1 addition): only once we've seen we can't cover
    # today's backlog with current workers, and only if it pays for itself
    # in the runway remaining.
    uncovered = sum(1 for t in tasks if (t["pos"], t.get("action")) not in used_tasks)
    if not in_liquidation and days_left >= 3 and uncovered > 0 and len(workers) < 4:
        hire_cost = fib_cost(farm.get("hires_today", 0) + 1)
        if money >= hire_cost + 200 and orders_used < max_orders:
            market_orders.append(["HIRE"])
            orders_used += 1

    # ---------- CONVERT ASSIGNMENTS TO ACTIONS ----------
    def action_for(wi):
        t = assigned[wi]
        wpos = workers[wi]
        if t is None:
            return ["PASS"]
        if wpos != t["pos"]:
            return [_step_toward(wpos, t["pos"])]
        if t["action"] == "PLANT":
            return ["PLANT", t["crop"]]
        if t["action"] in ("PLACE", "PICKUP"):
            return [t["action"], t["item"]]
        return [t["action"]]

    farmer_action = action_for(0)
    hands_actions = [action_for(i) for i in range(1, len(workers))]

    return {"farmer": farmer_action, "hands": hands_actions, "market": market_orders[:max_orders]}
