"""
Flattens agent/constants.py + agent/market.py + agent/policy.py into a single
ASCII-only, dependency-free file for Kaggle upload.

Why this exists: Kaggle's submission runner executes the uploaded file via a
raw compile()/exec(), which (a) rejects non-ASCII characters like em-dashes,
and (b) does NOT support the `sys.modules[__name__]` self-reference trick
that would normally let split modules re-join under aliases. So instead of
aliasing, this strips the `C.`/`M.` module-qualifier prefixes entirely and
flattens everything into one shared namespace.

Usage: python3 tools/bundle.py
Output: submission_bundle.py (upload this file to Kaggle)

IMPORTANT: always test the output with tests/run_matches.py in a FRESH,
ISOLATED directory (no agent/ package present) before uploading — a bundle
that imports cleanly next to agent/ can still be broken standalone.
"""
import re
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def strip_module_docstring_and_imports(text):
    text = re.sub(r'^\s*"""[\s\S]*?"""\s*\n', '', text, count=1)
    text = text.replace("from . import constants as C\n", "")
    text = text.replace("from . import market as M\n", "")
    return text


def strip_prefixes(text):
    text = re.sub(r'\bC\.', '', text)
    text = re.sub(r'\bM\.', '', text)
    return text


def main():
    const = open(os.path.join(ROOT, "agent/constants.py"), encoding="utf-8").read()
    mkt = open(os.path.join(ROOT, "agent/market.py"), encoding="utf-8").read()
    pol = open(os.path.join(ROOT, "agent/policy.py"), encoding="utf-8").read()

    const_body = strip_module_docstring_and_imports(const)
    mkt_body = strip_prefixes(strip_module_docstring_and_imports(mkt))
    pol_body = strip_prefixes(strip_module_docstring_and_imports(pol))

    bundle = '''"""
Kaggriculture submission - single-file bundle, auto-generated by
tools/bundle.py from agent/constants.py + agent/market.py + agent/policy.py.
Edit those files and re-run the bundler, not this file directly.
"""
import math as _math

# ---------------- constants ----------------
''' + const_body + '''

# ---------------- market ----------------
''' + mkt_body + '''

# ---------------- policy ----------------
''' + pol_body

    for bad, good in {"\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
                       "\u201c": '"', "\u201d": '"'}.items():
        bundle = bundle.replace(bad, good)

    bundle.encode("ascii")  # raise loudly if anything non-ASCII slipped through
    compile(bundle, "submission_bundle.py", "exec")  # raise loudly if it doesn't parse

    out_path = os.path.join(ROOT, "submission_bundle.py")
    with open(out_path, "w", encoding="ascii") as f:
        f.write(bundle)
    print(f"Wrote {out_path} ({len(bundle.splitlines())} lines). "
          f"Now test it in an isolated dir before uploading.")


if __name__ == "__main__":
    main()
